imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ChasseBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
  # Activate serializer for FOSRest
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    encryption: ssl
    auth_mode: login

    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ChasseBundle\Entity\User
    registration:
        form:
            type: ChasseBundle\Form\RegistrationType

    registration:
        confirmation:
            enabled: true
    from_email:
        address:        noreply@example.com
        sender_name:    Tag ton métier

# Easy Admin
easy_admin:
    entities:
        User:
            class: ChasseBundle\Entity\User
            label: 'Gestion utilisateurs'
            list:
                title: "Liste des utilisateurs / inscrits"
        Answer:
            class: ChasseBundle\Entity\Answer
            label: 'Base de mots'
            list:
                title: "Liste des mots inclus dans l'autocompletion"
        Job:
            class: ChasseBundle\Entity\Job
            label: 'Metiers'
            list:
                title: "Liste des métiers"
    design:
        menu:
            - { label: 'Espace AROM'}
            - { label: 'Statistique applications', route: 'stats' }
            - { label: 'Statistiques utilisateurs', route: 'userstats', params:{page:1}}
            - { label: 'Loterie', route: 'winner' }
            - { label: 'Gestion site'}
            - User
            - Answer
            - Job
