ChasseBundle\Entity\Answer:
    type: entity
    table: null
    repositoryClass: ChasseBundle\Repository\AnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        word:
            type: string
            length: 255
    lifecycleCallbacks: {  }
