ChasseBundle\Entity\User:
    type:  entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        interviews:
          targetEntity: Interview
          mappedBy: user