ChasseBundle\Entity\User:
    type:  entity
    table: user
    repositoryClass: ChasseBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        firstname:
            type: string
            length: 35
        lastname:
            type: string
            length: 35
        gender:
            type: string
            length: 10
        status:
            type: string
            length: 100
        age:
            type: smallint
        department:
            type: smallint
        newsletter:
            type: boolean
        satisfaction:
            type: smallint
            nullable: true
        comment:
            type: text
            nullable: true


    oneToMany:
        interviews:
          targetEntity: Interview
          mappedBy: user