index:
    path:     /
    defaults: { _controller: ChasseBundle:Front:index }

howto:
    path:     /regles-du-jeu
    defaults: { _controller: ChasseBundle:Front:howto }

legalmention:
    path:     /mentions-legales
    defaults: { _controller: ChasseBundle:Front:legalmention }

inscript:
    path:     /inscription
    defaults: { _controller: ChasseBundle:Front:inscript }


countdown:
    path:     /countdown
    defaults: { _controller: ChasseBundle:Front:countDown }

votevalid:
    path:     /votevalid
    defaults: { _controller: ChasseBundle:Front:voteValid }

learnmore:
    path:     /en-savoir-plus
    defaults: { _controller: ChasseBundle:Front:learnmore }

endpage:
    path:     /fin-du-jeu
    defaults: { _controller: ChasseBundle:Front:endpage }