job_index:
    path:     /
    defaults: { _controller: "ChasseBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{id}/show
    defaults: { _controller: "ChasseBundle:Job:show" }
    methods:  GET

job_new:
    path:     /new
    defaults: { _controller: "ChasseBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "ChasseBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "ChasseBundle:Job:delete" }
    methods:  DELETE

job_choose:
    path:     /choose/{domain}
    defaults: { _controller: "ChasseBundle:Job:jobchoose" }
    methods:  POST

job_select:
    path:     /select
    defaults: { _controller: "ChasseBundle:Job:jobselect" }
    methods:  [GET, POST]