<?php

namespace ChasseBundle\Repository;

/**
 * InterviewAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewAnswerRepository extends \Doctrine\ORM\EntityRepository
{
    //hackaton
    /*
        select i.job_id, ia.answer_id
        from interviews_answers ia
        inner join interview i
        on i.id = ia.interview_id
        where ia.answer_id = 239
        order by ia.answer_id
    */

    public function getJobListFromWord(/*$word*/) {
        $qb = $this->createQueryBuilder('ia')
            ->select('i.job_ib, ia.answerId')
            ->leftJoin('interview', 'i')
            ->where('ia.answerId = 239')
            //->setParameter($word, 'word')
        ;

        return $qb->getQuery()->getResult();
    }

}
