chasse_interview:
    resource: "@ChasseBundle/Resources/config/routing/interview.yml"
    prefix:   /interview


chasse_front:
    resource: "@ChasseBundle/Resources/config/routing/front.yml"
    prefix:   /

chasse_back:
    resource: "@ChasseBundle/Resources/config/routing/back.yml"
    prefix:   /back

add_data:
    path:     /add_data
    defaults: {_controller: ChasseBundle:Interview:data}