index:
    path:     /
    defaults: { _controller: ChasseBundle:Front:index }

howto:
    path:     /howto
    defaults: { _controller: ChasseBundle:Front:howto }

legalmention:
    path:     /legalmention
    defaults: { _controller: ChasseBundle:Front:legalmention }

inscript:
    path:     /inscript
    defaults: { _controller: ChasseBundle:Front:inscript }
