chasse_interview:
    resource: "@ChasseBundle/Resources/config/routing/interview.yml"
    prefix:   /interview

chasse_job:
    resource: "@ChasseBundle/Resources/config/routing/job.yml"
    prefix:   /job

index:
    path:     /
    defaults: { _controller: ChasseBundle:Front:index }

howto:
    path:     /regles-du-jeu
    defaults: { _controller: ChasseBundle:Front:howto }

legalmention:
    path:     /mentions-legales
    defaults: { _controller: ChasseBundle:Front:legalmention }

inscript:
    path:     /inscription
    defaults: { _controller: ChasseBundle:Front:inscript }


countdown:
    path:     /countdown
    defaults: { _controller: ChasseBundle:Front:countdown }